name: CI

on:
  create:
    tags:
      - v*
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull all history with tags for correct versionning
        run: git fetch --prune --unshallow
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.x
          distribution: zulu
      - name: Style checks
        run: ./mill all __.checkStyle __.docJar

  integration-kubernetes-v1-22:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Minikube and start Kubernetes
        uses: manusa/actions-setup-minikube@v2.6.1
        with:
          minikube version: v1.23.2
          kubernetes version: v1.22.1
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.x
          distribution: zulu
      - name: Test against Kubernetes v1.22
        run: ./mill __.test

  integration-kubernetes-v1-21:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Minikube and start Kubernetes
        uses: manusa/actions-setup-minikube@v2.6.1
        with:
          minikube version: v1.23.2
          kubernetes version: v1.21.5
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.x
          distribution: zulu
      - name: Test against Kubernetes v1.21
        run: ./mill __.test

  integration-kubernetes-v1-20:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Minikube and start Kubernetes
        uses: manusa/actions-setup-minikube@v2.6.1
        with:
          minikube version: v1.23.2
          kubernetes version: v1.20.11
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.x
          distribution: zulu
      - name: Test against Kubernetes v1.20
        run: ./mill __.test

  integration-kubernetes-v1-19:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Minikube and start Kubernetes
        uses: manusa/actions-setup-minikube@v2.6.1
        with:
          minikube version: v1.23.2
          kubernetes version: v1.19.15
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.x
          distribution: zulu
      - name: Test against Kubernetes v1.19
        run: ./mill __.test
